### ISSUE TITLE
if extension is xml, does not validate xml

### ISSUE THREAD

**Issue by valentinedwv** [opengeospatial/ets-19139#10]
That's my interpretation of org.opengis.cite.iso19139.InputValidator, line 65:

```
    public boolean extension(String pathSent, String extensionWanted) {

        String extensionWantedLower = extensionWanted.toLowerCase();
        String extensionWantedUpper = extensionWanted.toUpperCase();
        if (pathSent.endsWith(extensionWantedLower) || pathSent.endsWith(extensionWantedUpper)) {
            return true;
        } else {
          // Check whether the file contents are that of an XML file even if the extension doesn't say so

```

**Comment by dstenger** [comment]
@valentinedwv The content of the file is validated if the file extension does not match. So, the xml content itself is already validated.
Do you have any test service which can be used to reproduce the reported problem?

**Comment by dstenger** [comment]
@valentinedwv Is the reported bug still occurring? Otherwise, we will close this issue.

**Comment by lgoltz** [comment]
@valentinedwv Please reopen this issue if the problem still occurs.
