### ISSUE TITLE
As ISO changed the location of ISO_19139 schemas (ITTF) apiso.xsd can't be use for schema validation anymore

### ISSUE THREAD

**Issue by DeordD** [opengeospatial/ets-19139#20]
Hi all,

As you probably already know ISO moved ISO_19139 schemas (ITTF) to another [location](https://schemas.isotc211.org/schemas/19139/). Locations (import/includes) to new XSDs are not updated in http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd. 

Therefore apiso can't be used anymore for schema-validation. 

How did you solve respectively planning to deal with this in your project?

Any help is appreciated.      

Kind regards

**Comment by ghobona** [comment]
We will ask the OGC Infrastructure Office to update the links.

http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd would be updated to https://standards.iso.org/iso/19139/Schemas/gmd/gmd.xsd

We also noticed that ISO have not yet updated all of their XSDs. For example, https://standards.iso.org/iso/19139/Schemas/gmd/metadataApplication.xsd is still pointing to http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd

**Comment by ronaldtse** [comment]
@DeordD @ghobona the authoritative XML schema location for ISO/TC 211 is now:
https://schemas.isotc211.org/

All schemas there link correctly, e.g.
https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/metadataApplication.xsd
properly link to https://schemas.isotc211.org/19139/-/gco/1.0/gco.xsd

ping @ejbleys (ISO/TC 211 XML management group convener)

**Comment by ghobona** [comment]
@ronaldtse  @ejbleys 

I will need to ask the Joint Advisory Group (JAG) to confirm which of the two sets of schemas we should point to.

**Comment by ghobona** [comment]
We now have confirmation to use the schemas at https://schemas.isotc211.org/

**Comment by ronaldtse** [comment]
Thanks @ghobona !

**Comment by ghobona** [comment]
Update of this ETS will take place once the schemas on opengis.net have been updated to reference https://schemas.isotc211.org/

@kstegemoller Please let us know once the schemas on opengis.net have been updated.

**Comment by DeordD** [comment]
Hi @ghobona, @ronaldtse 

thanks a lot for your efforts! Nice to hear that communites will be able to use updated apiso schema soon.

Kind regards

**Comment by DeordD** [comment]
Hi @kstegemoller , @ghobona 

will updated apiso.xsd also be available directly on the [old url](http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd)? This would be good thing, because all XML files in SDI don't need to be changed for schemaLocation attribute and records can be validated directly!

I am also expecting that imported ISO schemas will start with https. This is important because many tools can't handle redirects (security aspects). 

Thanks a lot once more for your efforts!

**Comment by DeordD** [comment]
Hi @kstegemoller , @ghobona,

any news on this?

Kind regards

**Comment by iuriemaxim** [comment]
@ghobona Any news regarding apiso schema?

**Comment by kstegemoller** [comment]
apiso.xsd has been updated with the new ISO 19139 schemaLocation.

**Comment by DeordD** [comment]
@kstegemoller Thanks a lot for the update!

I have validate [this ISO19139 dataset](https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/Dataset_metadata_2.0_example.xml) in AltovaXML Spy 2018 with following result:
- some of referenced schemas in apiso.xsd are not valid
- metadata record is not valid even though this record is reference ISO 19139 metadata record.

One of many error messages (error messages manually translated from German to English):

```
Neither an element declaration nor a type declaration is known for the element <gmd: MD_Metadata>. The strict validation failed.
	Error path: gmd:MD_Metadata
	Details
		cvc-assess-elt.1: Neither an element declaration nor a type declaration is known for the element <gmd: MD_Metadata>. The strict validation failed.
```

**Comment by ghobona** [comment]
The file [Dataset_metadata_2.0_example.xml](https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/Dataset_metadata_2.0_example.xml) passes Schema Validation when I test it with Netbeans. The validator finds apiso.xsd.

The (truncated) log looks like:

```
XML validation started.
Checking file:/Users/ogc/Documents/NetBeansProjects/DM/src/main/java/Dataset_metadata_2.0_example.xml...
Referenced entity at "http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd".
Referenced entity at "https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd".

...several other referenced entities...

Referenced entity at "https://schemas.isotc211.org/19139/-/gmx/1.0/extendedTypes.xsd".
Referenced entity at "https://schemas.isotc211.org/19139/-/gmx/1.0/gmx.xsd".
XML validation finished.

```

**Comment by fabiovin** [comment]
Dear @DeordD,
I tested it with oXygen and it correctly validates.

**Comment by DeordD** [comment]
Hi everyone,

Geonetwork 3.10.3 and above can also validate the records which are having apiso.xsd in the xml header.

It seems that all tools which can validate the new apiso.xsd are using Xerces https://xerces.apache.org/xerces2-j/faq-xs.html.

It is really strange that Altova XMLSpy can't validate it.

**Comment by ghobona** [comment]
Moving to close this issue as the schemaLocations have been updated and validation has been verified using Oxygen, Netbeans and other tools.
