### ISSUE TITLE
Submission of metadata documents for validation instead of URLs

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-19139#4]
Not all metadata documents exist at URL's.
Add capability to submit a metadata document for validation

**Comment by bozyurt** [comment]
The metadata to be validated will be in XML and the request will be a HTTP POST.

**Comment by bermud** [comment]
The ISO XML record is generated on the fly from its MongoDB representation and passed as a POST body form field (iut) string value to

http://cite-dev-03.opengeospatial.org/teamengine/rest/suites/iso19139/1.0/run

I am getting 

HTTP/1.1 500 Internal Server Error [Date: Wed, 18 Feb 2015 23:13:33 GMT, Server: Apache, X-Frame-Options: SAMEORIGIN, Content-Type: text/html;charset=utf-8, Content-Language: en, Content-Length: 3680, Connection: close]
<html><head><title>Apache Tomcat/7.0.53 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
	com.sun.jersey.multipart.impl.MultiPartReaderClientSide.unquoteMediaTypeParameters(MultiPartReaderClientSide.java:244)
	com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:171)
	com.sun.jersey.multipart.impl.MultiPartReaderServerSide.readMultiPart(MultiPartReaderServerSide.java:80)
	com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:157)
	com.sun.jersey.multipart.impl.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:85)
	com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:490)
	com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:555)
	com.sun.jersey.multipart.impl.FormDataMultiPartDispatchProvider$FormDataInjectableValuesProvider.getInjectableValues(FormDataMultiPartDispatchProvider.java:122)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:183)
	com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.53 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.53</h3></body></html>

**Comment by bermud** [comment]
@aashishlodha @upendra-sachan @tanvi-shah  please review this issue!

**Comment by tanvi-shah** [comment]
Hi Luis. Could you please tell us what did you send in your POST body? Along with the values that you passed in parameters.

**Comment by bermud** [comment]
@bozyurt Can you please provide more details as requested by @tanvi-shah Thank you zoo much!!

**Comment by bozyurt** [comment]
I am passing a single parameter 'iut' having as value the content of the attached ISO XML file as string

to the POST body.

Burak

I. Burak Ozyurt, PhD
Associate Project Scientist
UCSD Dept of Psychiatry
9500 Gilman Drive MC 0855
La Jolla, CA 92093-0855
Tel: 858-246-0606
________________________________

**Comment by bozyurt** [comment]
I have attached the ISO xml file zipped again to prevent blocking of xml files by mail server.

Burak

I. Burak Ozyurt, PhD
Associate Project Scientist
UCSD Dept of Psychiatry
9500 Gilman Drive MC 0855
La Jolla, CA 92093-0855
Tel: 858-246-0606
________________________________

**Comment by upendra-sachan** [comment]
I have pushed the ISO19139 into amazon server(http://cite-dev-03.opengeospatial.org/teamengine/) as well as git-hub with solution of issue #4.

**Comment by upendra-sachan** [comment]
Step to perform solution:
Pass the ISO xml file and schematron file like this:
{"iut":"content of XML file",
"sch":"content of Schematron file"}
Use Content-Type: text/plain

**Comment by bermud** [comment]
@bozyurt , please let us know if this solution is working for you.
