### ISSUE TITLE
Java snippet to parse the results not found

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-19139#5]
@upendra-sachan  The java snippet in the read me file is not working. Please provide an example (Java or xslt) that can create a nice html of the results.

**Comment by upendra-sachan** [comment]
I updated an XSLT template into read me file, which convert XML result into
a html.

Thanks.


------
Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

*Email:* upendra.sachan@mindstix.com <blah@mindstix.com>
*Phone:* +91 8446253174
*Skype:* upendra.sachan1
