### ISSUE TITLE
gmi:MI_Metadata reported as invalid

### ISSUE THREAD

**Issue by valentinedwv** [opengeospatial/ets-19139#9]
http://cinergi.sdsc.edu/proxyXslt/?iut=http://hydro10.sdsc.edu/metadata/IEDA/10000_iso.xml

**Comment by bermud** [comment]
Apparently the validator is not throwing all the errors. These are expected:

Documents were not schema valid, 
* no date in citation.
* keywords as text nodes, and not in a keyword block
*  keywords blocks were empty. removed empty blocks
* TransferOptions empty, in which case, documents deleted.

**Comment by valentinedwv** [comment]
The latest ones should work, and throw the not gmd:MD_Metadata. 
They validate in XML oxygen.
The latest ones at: http://hydro10.sdsc.edu/metadata/IEDA/


Older one as prototypes (see: test_md in https://github.com/CINERGI/idea_fix )

**Comment by valentinedwv** [comment]
No gmi schemas in the application.
[https://github.com/opengeospatial/ets-19139/tree/master/src/main/resources/org/opengis/cite/iso19139/19139/]

matches:

[http://schemas.opengis.net/iso/]

but different than the iso repository
[http://www.isotc211.org/2005/Version.txt]

or the NOAA one:
[http://ngdc.noaa.gov/metadata/published/xsd/schema/]

**Comment by valentinedwv** [comment]
I need to read up, but I wonder if we can put the schema or if one exists, schemalocation from the input validation, into in the testcontext for the schema validation

**Comment by bermud** [comment]
@valentinedwv


Try level 3 and providing GMI schemas as a parameter. Read more here: https://github.com/opengeospatial/ets-19139/blob/master/README.md

**Comment by keshav-nangare** [comment]
@valentinedwv 

Can you please provide authoritative schematron's? So we can test the level 3 using this schematron.

**Comment by valentinedwv** [comment]
profile:
http://www.ngdc.noaa.gov/metadata/published/xsd/schema.xsd
directory:
http://www.ngdc.noaa.gov/metadata/published/xsd

**Comment by keshav-nangare** [comment]
We have updated the iso19139 with latest version on AWS server.

Following is the URL:
                                 http://cite-dev-03.opengeospatial.org/teamengine/
